### PR TITLE
Gamepad functionality added

### PR DESCRIPTION
**Pull request by RobertEGreenslade12**
You can now play with either a keyboard or a Gamepad. Do not play with both at the same time because we don't have any menu to set what controller you are using. I would test that playing with the keyboard still works because most of my testing went into using the controller. I tested with a PS4 controller. Other controller tests would be nice as well.

### CODE REVIEW

**Review by xsedim — DISMISSED** [review]
Overall, great work. I was able to hook up a PS3 controller and play with no trouble. I did find a number of issues when playtesting though:

Necessary changes:
- Player animations don't work at all when using keyboard. **(Resolved)**
- Player oneshot animations don't work for both keyboard and controller (ex. the sword attack is only one frame long). **(Resolved)**
- There is some timer logic in player classes that depends on methods only being called once per frame, but now those methods can be called twice per frame with two different controllers. For example, `PlayerSpriteManager.StandStill()` decrements the `immobilityTimer` which will now decrease twice as fast. **(Resolved)**

Nice-to-have changes:
- Reset and mute keys are missing from controller
- You mentioned this in the PR already, but ideally the keyboard and gamepad cannot be both used at the same time. Right now, you can hold right on the controller and keyboard to move twice as fast. **(Resolved)**
- I feel like deadzone should be slightly larger.
- An option to move around with the D-pad would be nice and pretty intuitive for the gameplay since movement is already 4-directional.

**Comment by bitblip** [comment]
You get a null ref exception if you press X or O buttons on a PS3 controller in the title screen.
Would be nice if the D-pad also controlled Links movement.

**Comment by xsedim** [comment]
> You get a null ref exception if you press X or O buttons on a PS3 controller in the title screen. 

Probably important to mention that I have previously downloaded custom drivers for PS3 controllers, so my PC thinks that they’re Xbox controllers. PS3 controllers in general don’t plug-and-play very well, so it’s most likely a fault of the controllers, not our program. Still work investigating, though.

**Comment by bitblip** [comment]
Connecting via Bluetooth does not work.

**Pull request merged**
