### PR TITLE
Spawn Link in Correct Position, Player Static Block Collision

### PR DESCRIPTION
**Pull request by joshua-klasmeier**
There is a "bug" that I will add to backlog to be resolved. When player collides with two collidables at once there is a gittering effect.

### CODE REVIEW

**Comment by OmKurkure** [comment]
Looks good

**Review by bitblip — DISMISSED** [review]
It would be good to clear out the unused reference warnings?

Not an immediate concern but running logic inside the command is an anti-pattern. Moving that logic into `PlayerCollision' object might lead to a solution for the double collision problem. PlayerCollision could better collect the collision demands of the player and make better decisions to resolve them in it's update.

**Review by RobertEGreenslade12 — APPROVED** [review]
Code looks to make sense for what we are trying to accomplish

**Comment by xsedim** [comment]
I agree with Josh that unused references should be removed before merging. It may be fine if they are planned to be used in the future, but it looks like an oversight in this case.

**Pull request merged**
